name: release
on:
  push:
    tags:
    - '*'

jobs:
  release: 
    runs-on: ubuntu-latest
    steps:
    # A name for your step to display on GitHub.
    - uses: actions/checkout@v1
    - name: insert api key
      run: |
        sed -i "s/API_KEY/${{ secrets.ANDROID_API_KEY }}/g" ./android/app/google-services.json
        sed -i "s/API_KEY/${{ secrets.WEB_API_KEY }}/g" ./web/index.html
    # Sets up a flutter environment.
    # https://github.com/marketplace/actions/flutter-action
    - uses: subosito/flutter-action@v1
      with:
        channel: 'beta' # or: 'dev' or 'beta'
    
    - name: bundle
      run: |
        gem install bundler
        cd android
        # echo "${{ secrets.SERVICE_ACCOUNT_JSON }}" | base64 --decode > ./access_key.json
        echo "${{ secrets.SIGN_KEY_JKS }}" | base64 --decode > ./sign_key.jks
        bundle exec fastlane build_android
        # bundle exec fastlane deploy_android alpha:true
        # rm ./access_key.json
        rm ./sign_key.jks
        cd ..
      env:
        ANDROID_KEYSTORE_PATH: ./sign_key.jks
        ANDROID_KEY_STORE_PASSWORD: ${{ secrets.ANDROID_KEY_STORE_PASSWORD }}
        ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
        ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

    - name: Create web app
      run: |
        flutter config --enable-web
        flutter build web --release
        
    

    - name: Deploy pages
      uses: JamesIves/github-pages-deploy-action@master
      env: 
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: build/web

    - name: Deploy google play store
      uses: r0adkll/upload-google-play@v1
      with:
        serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
        packageName: com.finside.realoptions
        releaseFile: build/app/outputs/bundle/release/app.aab
        track: alpha
        # userFraction: 0.33
        whatsNewDirectory: assets/whatsnew
        # mappingFile: build/outputs/mapping/release/mapping.txt

    - name: release files
      uses: ncipollo/release-action@v1
      with:
        artifacts: "./build/app/outputs/apk/release/*"
        # bodyFile: "body.md"
        token: ${{ secrets.ACCESS_TOKEN }}