# Name of your workflow.
name: tagtest
on: [push]
    
jobs:
  tag:
    runs-on: ubuntu-latest
    # Creates a build matrix for your jobs. You can define different
    # variations of an environment to run each job in.
    steps:
    # A name for your step to display on GitHub.
    - uses: actions/checkout@v1
    # Sets up a flutter environment.
    # https://github.com/marketplace/actions/flutter-action
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.25.0'
        channel: 'beta' # or: 'dev' or 'beta'
    - name: "Run Flutter Driver tests"
      run: |
        flutter pub get
        flutter clean
        flutter test --coverage
        bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
    - name: set flutter version
      run: echo "FLUTTER_VERSION=$(grep 'version:' pubspec.yaml | tail -n1 | cut -c 10-)" >> $GITHUB_ENV
    - name: get branch name
      run: echo "BRANCH_NAME=${GITHUB_REF##*/}" >> $GITHUB_ENV
    - name: get branch tag
      run: echo "RELEASE_TAG=$([ ${{ env.BRANCH_NAME }} == master ] && echo \"release\" || echo \"beta\")" >> $GITHUB_ENV
    - name: get tag
      run: echo "CUSTOM_TAG=${{ env.RELEASE_TAG }}-${{ env.FLUTTER_VERSION }} " >> $GITHUB_ENV
    - name: does tag exist
      run: echo "TAG_DOES_NOT_EXIST=$(git tag | grep -q ${{ env.CUSTOM_TAG }} ; echo $?)" >> $GITHUB_ENV
        
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.34.0
      if: env.TAG_DOES_NOT_EXIST=='1'
      env:
        GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        CUSTOM_TAG: ${{ env.CUSTOM_TAG }}
        RELEASE_BRANCHES: '.*'