# Name of your workflow.
name: test
on: [push, pull_request] # A workflow run is made up of one or more jobs.
jobs:
  test:
    runs-on: ubuntu-latest
    # Creates a build matrix for your jobs. You can define different
    # variations of an environment to run each job in.
    steps:
    # A name for your step to display on GitHub.
    - uses: actions/checkout@v1
    # Sets up a flutter environment.
    # https://github.com/marketplace/actions/flutter-action
    - uses: subosito/flutter-action@v1
      with:
        flutter_version: '1.14.6'
        channel: 'stable' # or: 'dev' or 'beta'
    - name: "Run Flutter Driver tests"
      run: |
        flutter pub get
        flutter clean
        flutter test --coverage
        bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
    - name: Create apk
      run: flutter build apk --split-per-abi