# Name of your workflow.
name: test
on: [push, pull_request] # A workflow run is made up of one or more jobs.
jobs:
  test:
    runs-on: ubuntu-latest
    # Creates a build matrix for your jobs. You can define different
    # variations of an environment to run each job in.
    steps:
    # A name for your step to display on GitHub.
    - uses: actions/checkout@v1
    # Sets up a flutter environment.
    # https://github.com/marketplace/actions/flutter-action
    - uses: subosito/flutter-action@v1
      with:
        flutter_version: '1.14.6'
        channel: 'beta' # or: 'dev' or 'beta'
    - name: "Run Flutter Driver tests"
      run: |
        flutter pub get
        flutter clean
        flutter test --coverage
        bash <(curl -s https://codecov.io/bash) -t ${{ secrets.CODECOV_TOKEN }}
    - name: build apk
      run: |
        flutter build apk --split-per-abi
    
    - name: set flutter version
      run: echo ::set-env name=FLUTTER_VERSION::$(grep 'version:' pubspec.yaml | tail -n1 | cut -c 10-)
    
    - name: does tag exist
      run: echo ::set-env name=TAG_DOES_NOT_EXIST::$(git tag | grep -q ${{ GITHUB_REF }}-${{ env.FLUTTER_VERSION }} ; echo $?)
    
    - name: Bump version and push tag
      if: env.TAG_DOES_NOT_EXIST
      uses: anothrNick/github-tag-action@1.17.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CUSTOM_TAG: ${{ GITHUB_REF }}-${{ env.FLUTTER_VERSION }}